---
openapi: 3.0.3
info:
  title: scRNA-Seq Gene Expression Endpoints
  version: 1.0.0
  description: |
    Endpoints supporting scRNA-Seq Gene Expression visualization. A synopsis of scRNA-Seq sequencing: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8964935/.
    The gene expression data has to go through a normalization process and that data is stored in HDF5 files. The data is stored as a matrix inside each HDF5
    file, with one dimension containing gene ids, and another dimension having cell identifiers.
servers:
  - url: https://api.gdc.cancer.gov
security:
  - auth-token-header: []
  - auth-token-cookie: []
components:
  securitySchemes:
    auth-token-header:
      type: apiKey
      in: header
      name: X-Auth-Token
      description: |
        (Optional) Acquired from the user profile after logging in at [GDC Portal](https://portal.gdc.cancer.gov/).
        Required for accessing any protected data.
    auth-token-cookie:
      type: apiKey
      in: cookie
      name: X-Auth-Token
      description: |
        (Optional) Acquired from the user profile after logging in at [GDC Portal](https://portal.gdc.cancer.gov/).
        Required for accessing any protected data.
  schemas:
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    ErrorsArray:
      type: array
      items:
        $ref: '#/components/schemas/Error'
    ResponseErrors:
      type: object
      required:
        - errors
      properties:
        errors:
          $ref: "#/components/schemas/ErrorsArray"
    Identifier:
      type: string
      format: uuid
      example: 94f90e9a-ecfe-4682-8d19-2ac88b31a5b8
    GeneID:
      type: string
      pattern: ^ENSG
      example: ENSG00000139618
    RequestGeneIDs:
      type: array
      minItems: 1
      maxItems: 10
      items:
        $ref: '#/components/schemas/GeneID'
    FileIdRequestObject:
      type: object
      required:
        - file_id
        - gene_ids
      properties:
        file_id:
          $ref: '#/components/schemas/Identifier'
        gene_ids:
          $ref: '#/components/schemas/RequestGeneIDs'
    CaseIdRequestObject:
      type: object
      required:
        - case_id
        - gene_ids
      properties:
        case_id:
          $ref: '#/components/schemas/Identifier'
        gene_ids:
          $ref: '#/components/schemas/RequestGeneIDs'
    ResponseCellsArray:
      type: array
      items:
        $ref: '#/components/schemas/ResponseCell'
    ResponseCell:
      type: object
      required:
        - cell_id
        - expression
      properties:
        cell_id:
          type: string
        expression:
          type: number
          format: double
    ResponseObject:
      type: object
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/ResponseCaseGeneObjectsArray'
    ResponseCaseGeneObjectsArray:
      type: array
      items:
        $ref: "#/components/schemas/ResponseCaseGeneObject"
    ResponseCaseGeneObject:
      type: object
      required:
        - case_id
        - file_id
        - gene_id
        - cells
        - errors
      properties:
        case_id:
          $ref: '#/components/schemas/Identifier'
        file_id:
          $ref: '#/components/schemas/Identifier'
        gene_id:
          $ref: '#/components/schemas/GeneID'
        cells:
          $ref: '#/components/schemas/ResponseCellsArray'
        errors:
          $ref: '#/components/schemas/ErrorsArray'
  examples:
    SuccessfulQuery:
      value:
        data:
          - case_id: 94f90e9a-ecfe-4682-8d19-2ac88b31a5b8
            file_id: 5b383196-0109-4452-8bce-459308d5b394
            gene_id: ENSG00000139618
            cells:
              - cell_id: AAACCCAAGCCACTCG-1
                expression: 0.693147
            errors: []
    UnauthorizedFileQuery:
      value:
        errors:
          - message: "Unauthorized - user does not have proper authorization for file 5b383196-0109-4452-8bce-459308d5b392 associated with case 94f90e9a-ecfe-4682-8d19-2ac88b31a5b8"
    CaseNotFoundQuery:
      value:
        errors:
          - message: "Not Found - case 94f90e9a-ecfe-4682-8d19-2ac88b31a5b8 does not exist"
    FileNotFoundQuery:
      value:
        errors:
          - message: "Not Found - file 7b688f18-2802-4892-a0df-3be06ec76958 is not an scRNA-Seq HDF5 file"
    CaseNoFiles:
      value:
        errors:
          - message: "Data Error - case 94f90e9a-ecfe-4682-8d19-2ac88b31a5b8 does not have any associated gene expression files"
    CaseTooManyFiles:
      value:
        errors:
          - message: "Data Error: case 94f90e9a-ecfe-4682-8d19-2ac88b31a5b8 has more than one associated gene expression file: [5b383196-0109-4452-8bce-459308d5b394, 5b383196-0109-4452-8bce-459308d5b387]"
    FileRedacted:
      value:
        errors:
         - message: "Data Error - file 5b383196-0109-4452-8bce-459308d5b392 associated with case 94f90e9a-ecfe-4682-8d19-2ac88b31a5b8 has been redacted"
    GeneNotFoundQuery:
      value:
        data:
          - case_id: 94f90e9a-ecfe-4682-8d19-2ac88b31a5b8
            file_id: 5b383196-0109-4452-8bce-459308d5b392
            gene_id: ENSG00000123456
            cells: []
            errors:
              - message: Data Error - cannot find data for gene ENSG00000123456
    MissingCaseOrFileID:
      value:
        errors:
          - message: Invalid Request - specify either case_id or file_id
    MissingGeneIDs:
      value:
        errors:
          - message: Invalid Request - gene_ids is a required field
    MissingCaseAndFileIDAndGeneErrors:
      value:
        errors:
          - message: Invalid Request - specify either case_id or file_id
    EmptyGeneIDs:
      value:
        errors:
          - message: Invalid Request - gene_ids requires at least 1 item
    BothCaseAndFileID:
      value:
        errors:
          - message: Invalid Request - specify either case_id or file_id, not both
    TooManyGeneIDs:
      value:
        errors:
          - message: Invalid Request - gene_ids can only have at most only 10 items
    CaseIDInvalid:
      value:
        errors:
          - message: Invalid Request - case_id must follow uuid format
    FileIDInvalid:
      value:
        errors:
          - message: Invalid Request - file_id must follow uuid format
    CaseAndGeneIDsInvalid:
      value:
        errors:
          - message: Invalid Request - case_id must follow uuid format
          - message: Invalid Request - gene_id must follow ENSEMBL format at index 0
    FileAndGeneIDsInvalid:
      value:
        errors:
          - message: Invalid Request - file_id must follow uuid format
          - message: Invalid Request - gene_id must follow ENSEMBL format at index 0
    GeneIDInvalid:
      value:
        errors:
          - message: Invalid Request - gene_id must follow ENSEMBL format at index 0
paths:
  /scrna_seq/gene_expression:
    post:
      summary: Get scRNA-Seq gene expression data.
      description: |
        For a single case, get gene expression data for all cell ids for the requested gene.
        Currently, the endpoint will only support 1 case and up to 10 genes.
      tags:
        - scRNA-Seq
      requestBody:
        description: |
          The case_id and file_id fields are mutually exclusive. At least one, but only one, of these
          fields can be specified in the request.
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/CaseIdRequestObject'
                - $ref: '#/components/schemas/FileIdRequestObject'
            examples:
              Case ID Request Example:
                value:
                  case_id: 94f90e9a-ecfe-4682-8d19-2ac88b31a5b8
                  gene_ids: [ENSG00000139618]
              File ID Request Example:
                value:
                  file_id: 7b688f18-2802-4892-a0df-3be06ec76958
                  gene_ids: [ENSG00000139618]
      responses:
        200:
          description: All or partial gene expression data returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseObject"
              examples:
                Successful Query:
                  $ref: '#/components/examples/SuccessfulQuery'
                Gene - No Data:
                  $ref: '#/components/examples/GeneNotFoundQuery'
        400:
          description: Invalid client request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseErrors'
              examples:
                Missing Case or File ID:
                  $ref: '#/components/examples/MissingCaseOrFileID'
                Missing Gene IDs:
                  $ref: '#/components/examples/MissingGeneIDs'
                Missing Case and File ID and gene errors:
                  $ref: '#/components/examples/MissingCaseAndFileIDAndGeneErrors'
                Empty Gene IDs:
                  $ref: '#/components/examples/EmptyGeneIDs'
                Both Case and File ID:
                  $ref: '#/components/examples/BothCaseAndFileID'
                Too Many Gene IDs:
                  $ref: '#/components/examples/TooManyGeneIDs'
                Case ID Invalid:
                  $ref: '#/components/examples/CaseIDInvalid'
                File ID Invalid:
                  $ref: '#/components/examples/FileIDInvalid'
                Case and Gene IDs Invalid:
                  $ref: '#/components/examples/CaseAndGeneIDsInvalid'
                File and Gene IDs Invalid:
                  $ref: '#/components/examples/FileAndGeneIDsInvalid'
                Invalid Gene ID:
                  $ref: '#/components/examples/GeneIDInvalid'
                Case - No Files:
                  $ref: '#/components/examples/CaseNoFiles'
                Case - Too Many Files:
                  $ref: '#/components/examples/CaseTooManyFiles'
        403:
          description: Unauthorized to access scRNA-Seq file
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseErrors'
              examples:
                File - Unauthorized:
                  $ref: '#/components/examples/UnauthorizedFileQuery'
        404:
          description: Case or File not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseErrors'
              examples:
                Case - Not Found:
                  $ref: '#/components/examples/CaseNotFoundQuery'
                File - Not Found:
                  $ref: '#/components/examples/FileNotFoundQuery'
        451:
          description: File not available due to legal reasons
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseErrors'
              examples:
                File - Redacted:
                  $ref: '#/components/examples/FileRedacted'
